development:
  name: blogme-api
  host: http://localhost:5000
  port: 5000
  mongodb:
    url: mongo url
    options: 
      useNewUrlParser: true
      useUnifiedTopology: true
      useCreateIndex: true
      useFindAndModify: false
  jwt: 
    secret: jwt secret
    options:
      algorithm: HS256
      audience: http://localhost:5000
      expiresIn: 2h