development:
  name: blogme-api
  host: http://localhost:5000
  port: 5000
  mongodb:
    url: mongodb+srv://Petchill:pe111333@youpin-0iyxk.gcp.mongodb.net/blogme
    options: 
      useNewUrlParser: true
      useUnifiedTopology: true
      useCreateIndex: true
      useFindAndModify: false
  jwt: 
    secret: 4b7K77jLYI3lRl61n6wN
    options:
      algorithm: HS256
      audience: http://localhost:5000
      expiresIn: 2h